
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q

from .models import Message, Room

User = get_user_model()

@login_required
def room(request, room_name):
    room, created = Room.objects.get_or_create(name=room_name, defaults={'slug': room_name})
    messages = Message.objects.filter(room=room).order_by('timestamp')[:50] # Last 50 messages


    return render(request, 'chat/room.html', {
        'room_name': room_name,
        'messages': messages
    })

@login_required
def rooms(request):
    """
    View to display the list of available users to chat with.
    """
    users = User.objects.exclude(id=request.user.id)
    return render(request, 'chat/rooms.html', {
        'all_users': users,
        'current_user': request.user
    })

@login_required
def start_private_chat(request, target_username):
    """
    Redirects to a private chat room between the current user and the target user.
    The room name is generated by sorting the usernames to ensure consistency.
    """
    current_username = request.user.username

    # Sort usernames to ensure the room name is the same regardless of who starts the chat
    participants = sorted([current_username, target_username])
    room_name = f"{participants[0]}_{participants[1]}"

    return redirect('chat:room', room_name=room_name)
