# Generated by Django 5.1.5 on 2025-11-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled', to='lms.course', verbose_name='Записанные курсы'),
        ),
    ]
