# Generated by Django 5.1.5 on 2025-11-27 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_user_enrolled_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название достижения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Иконка')),
                ('criteria_type', models.CharField(choices=[('course_count', 'Количество курсов'), ('test_score', 'Результат теста'), ('login_streak', 'Серия входов'), ('material_views', 'Просмотр материалов'), ('course_completion', 'Завершение курса')], max_length=50, verbose_name='Тип критерия')),
                ('criteria_value', models.IntegerField(verbose_name='Значение критерия')),
                ('points', models.IntegerField(default=10, verbose_name='Очки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс (0-100)')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
