# Generated by Django 5.2.9 on 2025-12-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_achievement_userachievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='material',
            name='content',
        ),
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.RemoveField(
            model_name='material',
            name='link',
        ),
        migrations.AddField(
            model_name='material',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('TEXT', 'Текст'), ('VIDEO', 'Видео'), ('CODE_SNIPPET', 'Пример кода'), ('FILE', 'Файл')], default='TEXT', max_length=20, verbose_name='Тип блока')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текстовый контент/Код')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/blocks/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lms.material', verbose_name='Материал')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
