# Generated by Django 5.2.9 on 2025-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_material_options_remove_material_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Метаданные (LeetCode/Jira style)'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('TEXT', 'Текст'), ('VIDEO', 'Видео'), ('CODE_SNIPPET', 'Пример кода'), ('FILE', 'Файл'), ('PRACTICE', 'Практика кода'), ('TASK', 'Задача')], default='TEXT', max_length=20, verbose_name='Тип блока'),
        ),
    ]
