# Generated by Django 5.2.9 on 2025-12-30 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_contentblock_metadata_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('input_data', models.TextField(verbose_name='Входные данные (тест)')),
                ('expected_output', models.TextField(verbose_name='Ожидаемый результат')),
                ('hints', models.TextField(blank=True, null=True, verbose_name='Подсказки')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательная для прогресса')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='lms.material', verbose_name='Урок/Материал')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код решения')),
                ('status', models.CharField(choices=[('PENDING', 'На проверке'), ('ACCEPTED', 'Принято'), ('REJECTED', 'На доработку'), ('FAILED', 'Ошибка выполнения')], default='PENDING', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв преподавателя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.codingproblem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
