# Generated by Django 5.2.9 on 2025-12-30 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_personaltask_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('current_xp', models.IntegerField(default=0, verbose_name='Опыт на уровне')),
                ('total_xp', models.IntegerField(default=0, verbose_name='Всего опыта')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Дней подряд')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Дата последней активности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
