# Generated by Django 5.2.9 on 2025-12-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='test_cases',
            field=models.JSONField(default=list, help_text='Список объектов с полями stdin, stdout, is_hidden, timeout', verbose_name='Тест-кейсы (JSON)'),
        ),
    ]
