# Generated by Django 6.0 on 2025-12-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0011_codingproblem_test_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingproblem",
            name="reference_solution",
            field=models.TextField(
                blank=True, null=True, verbose_name="Эталонное решение"
            ),
        ),
    ]
