# Generated by Django 6.0 on 2025-12-30 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0012_codingproblem_reference_solution"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("cost", models.IntegerField(default=100, verbose_name="Цена (монет)")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("THEME", "Тема редактора"),
                            ("FRAME", "Рамка аватара"),
                            ("UTILITY", "Утилита"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Метаданные (css_class/theme_name)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🛍️", max_length=50, verbose_name="Иконка"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="coins",
            field=models.IntegerField(default=0, verbose_name="Монеты"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="weekly_xp",
            field=models.IntegerField(default=0, verbose_name="Опыт за неделю"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("course_count", "Количество курсов"),
                    ("test_score", "Результат теста"),
                    ("login_streak", "Серия входов"),
                    ("material_views", "Просмотр материалов"),
                    ("course_completion", "Завершение курса"),
                    ("night_owl", "Ночная сова (решение после 2:00)"),
                    ("sniper", "Снайпер (с первой попытки)"),
                    ("marathon", "Марафонец (30 дней подряд)"),
                ],
                max_length=50,
                verbose_name="Тип критерия",
            ),
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название клана"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_clans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лидер",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="clan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="lms.clan",
                verbose_name="Клан",
            ),
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("is_equipped", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lms.shopitem"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="lms.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "item")},
            },
        ),
    ]
