# Generated by Django 6.0 on 2025-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0013_shopitem_studentprofile_coins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingproblem",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("EASY", "Легкая"),
                    ("MEDIUM", "Средняя"),
                    ("HARD", "Сложная"),
                ],
                default="EASY",
                max_length=10,
                verbose_name="Сложность",
            ),
        ),
        migrations.AddField(
            model_name="codingproblem",
            name="starter_code",
            field=models.TextField(blank=True, null=True, verbose_name="Начальный код"),
        ),
        migrations.AddField(
            model_name="material",
            name="xp_reward",
            field=models.IntegerField(default=10, verbose_name="Награда XP"),
        ),
    ]
